export const NAVIGATION = {
  LOGIN_SCREEN: 'NAVIGATION/LOGIN_SCREEN',
  HOME_SCREEN: 'NAVIGATION/HOME_SCREEN',
  SYSTEM_SCREEN: 'NAVIGATION/SYSTEM_SCREEN',
  KITCHEN_SCREEN: 'NAVIGATION/KITCHEN_SCREEN',
  COUNTER_SCREEN: 'NAVIGATION/COUNTER_SCREEN'
};

export const TEST_API = {
  TEST_REQUEST: 'TEST_REQUEST',
  TEST_SUCCESS: 'TEST_SUCCESS',
  TEST_FAILURE: 'TEST_FAILURE',
};
